#pragma once

#define ENCODERS_PAD_A { B6 }
#define ENCODERS_PAD_B { B5 }
#define ENCODERS_PAD_A_RIGHT { B5 }
#define ENCODERS_PAD_B_RIGHT { B6 }


#define PIMORONI_TRACKBALL_CLICK
#define PIMORONI_TRACKBALL_INVERT_X
#define PIMORONI_TRACKBALL_INVERT_Y
#define PIMORONI_TRACKBALL_ROTATE

#define MASTER_RIGHT
