OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no
MUSIC_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no

#HAPTIC FEEBACK
HAPTIC_ENABLE = yes

#PER KEY RGB
RGB_MATRIX_ENABLE = no

WPM_ENABLE         = yes

CUSTOM_SPLIT_TRANSPORT_SYNC = yes
